version: '3.1'

services:
  
  service:
    build:
      context: ..
      dockerfile: ./build/service.Dockerfile
    restart: on-failure
    ports:
      - 8086:8086

  client:
    build:
      context: ..
      dockerfile: ./build/client.Dockerfile
    restart: on-failure
    command: sh -c "$${BIN_FILE} -h service"
    depends_on:
      service:
        condition: service_started