// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.6
// source: stats_service.proto

package stats_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResponsePeriod int64 `protobuf:"varint,1,opt,name=response_period,json=responsePeriod,proto3" json:"response_period,omitempty"`
	RangeTime      int64 `protobuf:"varint,2,opt,name=range_time,json=rangeTime,proto3" json:"range_time,omitempty"`
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_stats_service_proto_rawDescGZIP(), []int{0}
}

func (x *StatsRequest) GetResponsePeriod() int64 {
	if x != nil {
		return x.ResponsePeriod
	}
	return 0
}

func (x *StatsRequest) GetRangeTime() int64 {
	if x != nil {
		return x.RangeTime
	}
	return 0
}

type StatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoadInfo    *LoadInfo    `protobuf:"bytes,1,opt,name=load_info,json=loadInfo,proto3" json:"load_info,omitempty"`
	CpuInfo     *CPUInfo     `protobuf:"bytes,2,opt,name=cpu_info,json=cpuInfo,proto3" json:"cpu_info,omitempty"`
	DiskInfo    *DiskInfo    `protobuf:"bytes,3,opt,name=disk_info,json=diskInfo,proto3" json:"disk_info,omitempty"`
	TalkersInfo *TalkersInfo `protobuf:"bytes,4,opt,name=talkers_info,json=talkersInfo,proto3" json:"talkers_info,omitempty"`
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_stats_service_proto_rawDescGZIP(), []int{1}
}

func (x *StatsResponse) GetLoadInfo() *LoadInfo {
	if x != nil {
		return x.LoadInfo
	}
	return nil
}

func (x *StatsResponse) GetCpuInfo() *CPUInfo {
	if x != nil {
		return x.CpuInfo
	}
	return nil
}

func (x *StatsResponse) GetDiskInfo() *DiskInfo {
	if x != nil {
		return x.DiskInfo
	}
	return nil
}

func (x *StatsResponse) GetTalkersInfo() *TalkersInfo {
	if x != nil {
		return x.TalkersInfo
	}
	return nil
}

type LoadInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Load_1Min  float64 `protobuf:"fixed64,1,opt,name=load_1min,json=load1min,proto3" json:"load_1min,omitempty"`
	Load_5Min  float64 `protobuf:"fixed64,2,opt,name=load_5min,json=load5min,proto3" json:"load_5min,omitempty"`
	Load_15Min float64 `protobuf:"fixed64,3,opt,name=load_15min,json=load15min,proto3" json:"load_15min,omitempty"`
}

func (x *LoadInfo) Reset() {
	*x = LoadInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadInfo) ProtoMessage() {}

func (x *LoadInfo) ProtoReflect() protoreflect.Message {
	mi := &file_stats_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadInfo.ProtoReflect.Descriptor instead.
func (*LoadInfo) Descriptor() ([]byte, []int) {
	return file_stats_service_proto_rawDescGZIP(), []int{2}
}

func (x *LoadInfo) GetLoad_1Min() float64 {
	if x != nil {
		return x.Load_1Min
	}
	return 0
}

func (x *LoadInfo) GetLoad_5Min() float64 {
	if x != nil {
		return x.Load_5Min
	}
	return 0
}

func (x *LoadInfo) GetLoad_15Min() float64 {
	if x != nil {
		return x.Load_15Min
	}
	return 0
}

type CPUInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User   float64 `protobuf:"fixed64,1,opt,name=user,proto3" json:"user,omitempty"`
	System float64 `protobuf:"fixed64,2,opt,name=system,proto3" json:"system,omitempty"`
	Idle   float64 `protobuf:"fixed64,3,opt,name=idle,proto3" json:"idle,omitempty"`
}

func (x *CPUInfo) Reset() {
	*x = CPUInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CPUInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPUInfo) ProtoMessage() {}

func (x *CPUInfo) ProtoReflect() protoreflect.Message {
	mi := &file_stats_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPUInfo.ProtoReflect.Descriptor instead.
func (*CPUInfo) Descriptor() ([]byte, []int) {
	return file_stats_service_proto_rawDescGZIP(), []int{3}
}

func (x *CPUInfo) GetUser() float64 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *CPUInfo) GetSystem() float64 {
	if x != nil {
		return x.System
	}
	return 0
}

func (x *CPUInfo) GetIdle() float64 {
	if x != nil {
		return x.Idle
	}
	return 0
}

type DiskInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kbt float64 `protobuf:"fixed64,1,opt,name=kbt,proto3" json:"kbt,omitempty"`
	Tps float64 `protobuf:"fixed64,2,opt,name=tps,proto3" json:"tps,omitempty"`
}

func (x *DiskInfo) Reset() {
	*x = DiskInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskInfo) ProtoMessage() {}

func (x *DiskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_stats_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskInfo.ProtoReflect.Descriptor instead.
func (*DiskInfo) Descriptor() ([]byte, []int) {
	return file_stats_service_proto_rawDescGZIP(), []int{4}
}

func (x *DiskInfo) GetKbt() float64 {
	if x != nil {
		return x.Kbt
	}
	return 0
}

func (x *DiskInfo) GetTps() float64 {
	if x != nil {
		return x.Tps
	}
	return 0
}

type TalkersInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Top1 string `protobuf:"bytes,1,opt,name=top1,proto3" json:"top1,omitempty"`
	Top2 string `protobuf:"bytes,2,opt,name=top2,proto3" json:"top2,omitempty"`
	Top3 string `protobuf:"bytes,3,opt,name=top3,proto3" json:"top3,omitempty"`
}

func (x *TalkersInfo) Reset() {
	*x = TalkersInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TalkersInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TalkersInfo) ProtoMessage() {}

func (x *TalkersInfo) ProtoReflect() protoreflect.Message {
	mi := &file_stats_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TalkersInfo.ProtoReflect.Descriptor instead.
func (*TalkersInfo) Descriptor() ([]byte, []int) {
	return file_stats_service_proto_rawDescGZIP(), []int{5}
}

func (x *TalkersInfo) GetTop1() string {
	if x != nil {
		return x.Top1
	}
	return ""
}

func (x *TalkersInfo) GetTop2() string {
	if x != nil {
		return x.Top2
	}
	return ""
}

func (x *TalkersInfo) GetTop3() string {
	if x != nil {
		return x.Top3
	}
	return ""
}

var File_stats_service_proto protoreflect.FileDescriptor

var file_stats_service_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x74, 0x61, 0x74, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x73, 0x74, 0x61, 0x74, 0x73, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x22, 0x56, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x5f, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xed, 0x01, 0x0a,
	0x0d, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34,
	0x0a, 0x09, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x6c, 0x6f, 0x61, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x31, 0x0a, 0x08, 0x63, 0x70, 0x75, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x50, 0x55, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07,
	0x63, 0x70, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x34, 0x0a, 0x09, 0x64, 0x69, 0x73, 0x6b, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x74, 0x61,
	0x74, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x69, 0x73, 0x6b, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x08, 0x64, 0x69, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x3d, 0x0a,
	0x0c, 0x74, 0x61, 0x6c, 0x6b, 0x65, 0x72, 0x73, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x54, 0x61, 0x6c, 0x6b, 0x65, 0x72, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x0b, 0x74, 0x61, 0x6c, 0x6b, 0x65, 0x72, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x63, 0x0a, 0x08,
	0x4c, 0x6f, 0x61, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x6f, 0x61, 0x64,
	0x5f, 0x31, 0x6d, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x6f, 0x61,
	0x64, 0x31, 0x6d, 0x69, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x35, 0x6d,
	0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x6f, 0x61, 0x64, 0x35, 0x6d,
	0x69, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x31, 0x35, 0x6d, 0x69, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x61, 0x64, 0x31, 0x35, 0x6d, 0x69,
	0x6e, 0x22, 0x49, 0x0a, 0x07, 0x43, 0x50, 0x55, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x06, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x64, 0x6c, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x69, 0x64, 0x6c, 0x65, 0x22, 0x2e, 0x0a, 0x08,
	0x44, 0x69, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x62, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6b, 0x62, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x70,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x74, 0x70, 0x73, 0x22, 0x49, 0x0a, 0x0b,
	0x54, 0x61, 0x6c, 0x6b, 0x65, 0x72, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x6f, 0x70, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x6f, 0x70, 0x31, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x6f, 0x70, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x6f, 0x70, 0x32, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x6f, 0x70, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x6f, 0x70, 0x33, 0x32, 0x5e, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4e, 0x0a, 0x0f, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x1b, 0x2e, 0x73, 0x74, 0x61,
	0x74, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x1f, 0x5a, 0x1d, 0x2e, 0x2f, 0x73, 0x74, 0x61,
	0x74, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x3b, 0x73, 0x74, 0x61, 0x74, 0x73,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_stats_service_proto_rawDescOnce sync.Once
	file_stats_service_proto_rawDescData = file_stats_service_proto_rawDesc
)

func file_stats_service_proto_rawDescGZIP() []byte {
	file_stats_service_proto_rawDescOnce.Do(func() {
		file_stats_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_stats_service_proto_rawDescData)
	})
	return file_stats_service_proto_rawDescData
}

var file_stats_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_stats_service_proto_goTypes = []interface{}{
	(*StatsRequest)(nil),  // 0: stats_service.StatsRequest
	(*StatsResponse)(nil), // 1: stats_service.StatsResponse
	(*LoadInfo)(nil),      // 2: stats_service.LoadInfo
	(*CPUInfo)(nil),       // 3: stats_service.CPUInfo
	(*DiskInfo)(nil),      // 4: stats_service.DiskInfo
	(*TalkersInfo)(nil),   // 5: stats_service.TalkersInfo
}
var file_stats_service_proto_depIdxs = []int32{
	2, // 0: stats_service.StatsResponse.load_info:type_name -> stats_service.LoadInfo
	3, // 1: stats_service.StatsResponse.cpu_info:type_name -> stats_service.CPUInfo
	4, // 2: stats_service.StatsResponse.disk_info:type_name -> stats_service.DiskInfo
	5, // 3: stats_service.StatsResponse.talkers_info:type_name -> stats_service.TalkersInfo
	0, // 4: stats_service.StatsService.StatsMonitoring:input_type -> stats_service.StatsRequest
	1, // 5: stats_service.StatsService.StatsMonitoring:output_type -> stats_service.StatsResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_stats_service_proto_init() }
func file_stats_service_proto_init() {
	if File_stats_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_stats_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stats_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stats_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stats_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CPUInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stats_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiskInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stats_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TalkersInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stats_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stats_service_proto_goTypes,
		DependencyIndexes: file_stats_service_proto_depIdxs,
		MessageInfos:      file_stats_service_proto_msgTypes,
	}.Build()
	File_stats_service_proto = out.File
	file_stats_service_proto_rawDesc = nil
	file_stats_service_proto_goTypes = nil
	file_stats_service_proto_depIdxs = nil
}
